---
title: "txt"
author: "D&D"
date: "June 14, 2017"
output: html_document
---

<div style="text-align: right">

<h1> :גורמים המשפיעים על צריכת חשמל   </h1>
<h2>  מקרה נקודתי, שכונה באילת </h2>
</br>
<h3> הקדמה לנושא</h3>
</br> </br> 
<p>
התפתחות החברה האנושית בעת המודרנית גורמת לשינויים רבים במערכת האקולוגית והסביבה הטבעית. </br>הסיבה לשינויים אלו טמונה בביקוש ההולך וגדל למשאבי טבע אשר נועדו </br>לרווחתו של  האדם לצורך שיפור איכות החיים. </br>כתוצאה מכך המערכות האקולוגיות נפגעות. מערכות אקולוגיות אלו מספקות לאדם שירותי סביבה שונים ומגוונים כגון </br>ייצור מזן, ויסות טמפרטורה וטיהור מים.  שירותי הסביבה משפיעים בין אם באופן ישיר </br>או עקיף על רווחתו של האדם. אם כן, שמירה על המערכות האקולוגיות והסביבה הטבעית </br>חיונית לרווחות של האדם וקיימות החברה האנושית. (MEA 2005)</br>
</p>
<p>
תהליך ייצור האנרגיה מביא לפליטת מזהמי אוויר וגזי חממה היוצרים השפעות מקומיות, </br> אזוריות וגלובאליות ביניהן ההתחממות הגלובאלית. (ipcc 2014)</br>
</br> </br>
צריכת חשמל במשקי הבית </br> </br>
צריכת החשמל במשקי הבית מונעת על ידי הדיירים אשר להם התנהגות והרגלים סובייקטיביים. </br>על התנהגות זו משפיעים שלל גורמים סוציו-אקונומיים ופיזיים אשר מעצבים את האופן </br> וכמות האנרגיה הנצרכת. </br> </br>
המצב הכלכלי של משק הבית הינו אחד הגורמים הנחקרים ביותר כמשפיע על צריכת האנרגיה </br>והחשמל בפרט של משק הבית. מחקרים מראים כי מעמד כלכלי גבוה יותר מביא לעליה  </br> בצריכת החשמל (Yohanis, 2013). </br>
מעמד כלכלי משפיע על גורמים נוספים אשר להם השפעה בין אם ישירה או עקיפה על צריכה זו. </br> ככל  שהכנסתו של משק הבית עולה כך עולה מספר המכשירים החשמליים הנמצאים בבית  (Yohanis, 2013) .  </br> העלייה בהכנסה מביאה להגדלת שטח בית המגורים, עליה בשטחו של בית המגורים מביאה לצריכת חשמל גבוהה יותר (Santamouris et al., 2007) . </br>
</p>
<p>
מחקרים אשר בחנו את צריכת החשמל במשקי הבית בדירות מגורים ובתים צמודי הקרקע הראו </br>כי בתי הדירות צורכים פחות חשמל בשל שטחם הקטן יחסית (McLoughlin et al., 2012). </br>בהשוואת הצריכה בין בתי מגורים חדשים אשר מאופיינים בתקנות בנייה חדשות ויעילות טכנולוגית לבתים ישנים, נמצא כי משקי בית בעלי מעמד סוציו-אקונומי גבוה הינם צרכני חשמל </br>גדולים יותר למרות שאלו מתגוררים לרוב בבתי מגורים חדשים ((Santamouris et al., 2007)). </br>
</p>





</div>